dataHandler:
  # the folder of KITTI datasets
  # dataset_folder: "your_path_to_dataset/dataset_full"
  dataset_folder: "/home/mjy/datasets/overlapnet_datasets/OverlapNet/kitti/dataset_full/"

  # # the folder of raw semantic predictions
  # semantic_folder: "data/semantic_probs"
  # the folder to store the generated data
  # dst_folder: "data/preprocess_data_demo"
  use_depth: True
  use_intensity: True
  use_normals: True


trainHandler:
  train_seqs: ["07","02"]
  valid_seqs: ["02"]